apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "benthos-captain.fullname" . }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: benthos-captain
    app.kubernetes.io/part-of: benthos-captain
  {{- include "benthos-captain.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.deployment.serviceAccount.annotations | nindent 4 }}
