# permissions for end users to edit benthospipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: benthospipeline-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: benthos-operator
    app.kubernetes.io/part-of: benthos-operator
    app.kubernetes.io/managed-by: kustomize
  name: benthospipeline-editor-role
rules:
- apiGroups:
  - streaming.benthos.dev
  resources:
  - benthospipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.benthos.dev
  resources:
  - benthospipelines/status
  verbs:
  - get
