apiVersion: streaming.benthos.dev/v1alpha1
kind: BenthosPipeline
metadata:
  labels:
    app.kubernetes.io/name: benthospipeline
    app.kubernetes.io/instance: benthospipeline-sample
    app.kubernetes.io/part-of: benthos-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: benthos-operator
  name: benthospipeline-sample
spec:
  replicas: 10
  config: |
    input:
      generate:
        mapping: root = "woof"
        interval: 5s
        count: 0

    pipeline:
      processors:
        - mapping: root = content().uppercase()

    output:
      stdout: {}
