name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  GOLANG_VERSION: "1.22.x"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          args: --timeout=10m

      - name: Test
        run: make test

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Release
        run: |
          make docker-buildx IMG=ghcr.io/benthosdev/benthos-captain:${{github.ref_name}}
          make docker-buildx IMG=ghcr.io/benthosdev/benthos-captain:latest
