name: Release

on:
  push:
    tags:
      - "v*"

env:
  GOLANG_VERSION: "1.20.x"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Test
        run: make test

      - name: Release
        run: make docker-buildx IMG=ghcr.io/benthosdev/benthos-captain:${{github.ref_name}}
